### ISSUE TITLE
Can't create files if there are no files

### ISSUE THREAD

**Issue by yonatanmgr** [yonatanmgr/mathberet#4]
As title says, if the user has no files or folders in .../Documents/Mathberet/files, an error pops up and files can't be created

**Comment by alex-laycalvert** [comment]
Hey there, my names Alex and I thought this project was interesting. I did some digging and it looks like this issue is caused by the `generateStateWithNewFile` and `generateStateWithNewFolder` functions used when adding new files and folders.

When the initial check `if (focusedItem) { ... }`, it only checks if the `focusedItem` argument is null or undefined, NOT if it is an invalid index. The argument that is actually passed if there is no focused item is `-1` so the correct check for both of these functions should be 

```typescript
if (focusedItem >= 0) {
    // ...
}
```

I have a small fix but there are a few other issues I'm having while using the application that I can't tell if they are related or not so wanted to get in contact with you before submitting anything.

Best,
Alex

**Comment by alex-laycalvert** [comment]
I also didn't know if you or someone was already working on this and just figured I'd check before trying to contribute.

**Comment by yonatanmgr** [comment]
Hey Alex, thank you very much for your detailed response! This could very much be the case, will check this ASAP.

**Comment by zivnadel** [comment]
Is this being worked on?

**Comment by yonatanmgr** [comment]
@zivnadel Not currently! Do you want to work on this?

**Comment by zivnadel** [comment]
Yes

**Comment by yonatanmgr** [comment]
Assigning you

**Comment by yonatanmgr** [comment]
Fixed by #24 thanks to @zivnadel
